name: Benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

env:
  DEFAULT_GO_VERSION: "~1.26.0"
jobs:
  # Related issue: https://github.com/CodSpeedHQ/codspeed-go/issues/51
  sharding-benchmark:
    name: Sharding benchmarks
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.sharding.outputs.shards }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - id: sharding
        run: |
          echo "shards=$(make print-sharded-benchmarks)" >> $GITHUB_OUTPUT

  benchmark:
    needs: sharding-benchmark
    permissions:
      contents: write # required for pushing to gh-pages branch
    name: Benchmarks
    runs-on: oracle-bare-metal-64cpu-512gb-x86-64
    strategy:
      matrix:
        shard: ${{ fromJson(needs.sharding-benchmark.outputs.shards) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4.10.1
        with:
          mode: walltime
          allow-empty: true
          # CodSpeed overrides the default benchtime if we don't explicitly specify it.
          # Having this would avoid running benchmark for more than 1 hour.
          run: make benchmark/${{matrix.shard}} ARGS=-benchtime=1s
